//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clonePetService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillingService()
        {
            this.Advs = new HashSet<Adv>();
        }
    
        public int Id { get; set; }
        public string service_Name { get; set; }
        public string Customer_Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> Urgent { get; set; }
        public string NamePet { get; set; }
        public string Species { get; set; }
        public string Alike { get; set; }
        public Nullable<int> OldPet { get; set; }
        public Nullable<int> Weightcapacity { get; set; }
        public string Note { get; set; }
        public Nullable<int> TotaAmount { get; set; }
        public Nullable<int> User_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adv> Advs { get; set; }
        public virtual User User { get; set; }
    }
}
